name = input('What is your first name? ')
print(name + '?' + ' What a stupid fucking name.')
color = input('What is your favorite color? ')
print('Are you kidding me? ' + color + '? So many better choices.')
subject = input('Whats your favorite subject in school? ')
print('Wow. I cant believe you said ' + subject + ' as your favorite subject. I fucking despise you.')